import { spawn, type ChildProcess } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { killTree } from '../exec/terminal';
import type { ModelRecord } from '../models/registry';

/**
 * Persistent local eval server per model (NOT one-shot scripts — reloading a
 * multi-GB model per message would cost 30–120s each turn). The shipped
 * Python template loads base+adapter once and serves /generate on localhost;
 * we spawn it via uv inside the model's original training venv (deps already
 * there), health-check, proxy, and idle-kill after 10 minutes.
 */

const IDLE_KILL_MS = 10 * 60_000;
const LOAD_TIMEOUT_MS = 180_000;

interface EvalServerHandle {
  modelId: string;
  port: number;
  child: ChildProcess;
  lastUsed: number;
  ready: Promise<void>;
}

const g = globalThis as unknown as { __ftEvalServers?: Map<string, EvalServerHandle> };
const servers = (g.__ftEvalServers ??= new Map<string, EvalServerHandle>());

// Idle sweeper (module-level; re-armed after HMR by first import).
const gt = globalThis as unknown as { __ftEvalSweeper?: ReturnType<typeof setInterval> };
if (!gt.__ftEvalSweeper) {
  gt.__ftEvalSweeper = setInterval(() => {
    for (const [id, h] of servers) {
      if (Date.now() - h.lastUsed > IDLE_KILL_MS) {
        if (h.child.pid) killTree(h.child.pid);
        servers.delete(id);
      }
    }
  }, 60_000);
}

export async function ensureEvalServer(model: ModelRecord, workspaceDir: string): Promise<EvalServerHandle> {
  const existing = servers.get(model.id);
  if (existing && existing.child.exitCode === null) {
    existing.lastUsed = Date.now();
    await existing.ready;
    return existing;
  }
  servers.delete(model.id);

  // Ship the template into the workspace (kept under scripts/, harness-owned).
  const scriptPath = path.join(workspaceDir, 'scripts', '_eval_server.py');
  mkdirSync(path.dirname(scriptPath), { recursive: true });
  writeFileSync(scriptPath, EVAL_SERVER_PY, 'utf8');

  const port = 30_000 + Math.floor(Math.random() * 10_000);
  const child = spawn(
    `uv run python scripts/_eval_server.py --model "${model.adapterPath}" --base "${model.baseModel}" --port ${port}`,
    { shell: true, cwd: workspaceDir, windowsHide: true },
  );
  let bootLog = '';
  child.stdout?.on('data', (c: Buffer) => (bootLog = (bootLog + c.toString()).slice(-2000)));
  child.stderr?.on('data', (c: Buffer) => (bootLog = (bootLog + c.toString()).slice(-2000)));

  const ready = (async () => {
    const deadline = Date.now() + LOAD_TIMEOUT_MS;
    for (;;) {
      if (child.exitCode !== null) {
        throw new Error(`eval server exited (code ${child.exitCode}): ${bootLog.slice(-600)}`);
      }
      try {
        const res = await fetch(`http://127.0.0.1:${port}/health`, { signal: AbortSignal.timeout(2_000) });
        if (res.ok) return;
      } catch {
        // not up yet
      }
      if (Date.now() > deadline) {
        if (child.pid) killTree(child.pid);
        throw new Error(`eval server did not become healthy in ${LOAD_TIMEOUT_MS / 1000}s: ${bootLog.slice(-600)}`);
      }
      await new Promise((r) => setTimeout(r, 1_500));
    }
  })();

  const handle: EvalServerHandle = { modelId: model.id, port, child, lastUsed: Date.now(), ready };
  servers.set(model.id, handle);
  await ready;
  return handle;
}

export async function generate(
  model: ModelRecord,
  workspaceDir: string,
  messages: { role: string; content: string }[],
  maxNewTokens = 256,
): Promise<string> {
  const handle = await ensureEvalServer(model, workspaceDir);
  handle.lastUsed = Date.now();
  const res = await fetch(`http://127.0.0.1:${handle.port}/generate`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ messages, max_new_tokens: maxNewTokens }),
    signal: AbortSignal.timeout(300_000), // CPU generation can be slow
  });
  if (!res.ok) throw new Error(`generate failed: HTTP ${res.status} ${await res.text().catch(() => '')}`);
  const json = (await res.json()) as { text?: string; error?: string };
  if (json.error) throw new Error(json.error);
  return json.text ?? '';
}

const EVAL_SERVER_PY = `# Auto-generated by FineTune Studio — persistent eval server.
# Loads base+adapter ONCE, serves POST /generate on localhost.
import argparse, json
from http.server import BaseHTTPRequestHandler, HTTPServer

parser = argparse.ArgumentParser()
parser.add_argument("--model", required=True)   # adapter/model dir
parser.add_argument("--base", required=True)    # base model HF id
parser.add_argument("--port", type=int, required=True)
args = parser.parse_args()

import os
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

device = "cuda" if torch.cuda.is_available() else "cpu"
dtype = torch.bfloat16 if device == "cuda" else torch.float32
print(f"loading base={args.base} adapter={args.model} on {device}", flush=True)

is_adapter = os.path.exists(os.path.join(args.model, "adapter_config.json"))
tok_src = args.model if os.path.exists(os.path.join(args.model, "tokenizer_config.json")) else args.base
tokenizer = AutoTokenizer.from_pretrained(tok_src)
if is_adapter:
    from peft import PeftModel
    model = AutoModelForCausalLM.from_pretrained(args.base, torch_dtype=dtype, device_map=device)
    model = PeftModel.from_pretrained(model, args.model)
else:
    model = AutoModelForCausalLM.from_pretrained(args.model, torch_dtype=dtype, device_map=device)
model.eval()
print("model loaded", flush=True)

class Handler(BaseHTTPRequestHandler):
    def log_message(self, *a):  # quiet
        pass

    def _send(self, code, obj):
        body = json.dumps(obj).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        if self.path == "/health":
            self._send(200, {"ok": True, "device": device})
        else:
            self._send(404, {"error": "not found"})

    def do_POST(self):
        if self.path != "/generate":
            self._send(404, {"error": "not found"})
            return
        try:
            length = int(self.headers.get("Content-Length", 0))
            req = json.loads(self.rfile.read(length) or b"{}")
            messages = req.get("messages") or [{"role": "user", "content": req.get("prompt", "")}]
            max_new = int(req.get("max_new_tokens", 256))
            if hasattr(tokenizer, "apply_chat_template") and tokenizer.chat_template:
                prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
            else:
                prompt = "\\n".join(f"{m['role']}: {m['content']}" for m in messages) + "\\nassistant:"
            inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
            with torch.no_grad():
                out = model.generate(**inputs, max_new_tokens=max_new, do_sample=True, temperature=0.7, top_p=0.9,
                                     pad_token_id=tokenizer.pad_token_id or tokenizer.eos_token_id)
            text = tokenizer.decode(out[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True)
            self._send(200, {"text": text})
        except Exception as e:  # noqa: BLE001
            self._send(500, {"error": str(e)})

print(f"serving on 127.0.0.1:{args.port}", flush=True)
HTTPServer(("127.0.0.1", args.port), Handler).serve_forever()
`;
