import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { z } from 'zod';
import { registerTool } from './index';
import { resolveInWorkspace } from '../../paths';
import { runForeground } from '../../exec/terminal';

/**
 * Publish a trained model to the Hugging Face Hub. ALWAYS approval-gated
 * (D6) — publishing is outward-facing. Uses huggingface_hub.upload_folder via
 * a shipped script (multi-GB LFS uploads are a solved problem there; a TS
 * reimplementation would be the riskiest possible wheel to reinvent).
 * HF_TOKEN travels via env, never argv.
 */

const UPLOAD_PY = `# Auto-generated by FineTune Studio — HF upload helper.
import argparse, os, sys
from huggingface_hub import HfApi

p = argparse.ArgumentParser()
p.add_argument("--folder", required=True)
p.add_argument("--repo", required=True)
p.add_argument("--private", action="store_true")
p.add_argument("--message", default="Upload from FineTune Studio")
a = p.parse_args()

token = os.environ.get("HF_TOKEN")
if not token:
    print("HF_TOKEN missing in environment", file=sys.stderr)
    sys.exit(2)

api = HfApi(token=token)
repo = api.create_repo(repo_id=a.repo, exist_ok=True, private=a.private).repo_id
api.upload_folder(folder_path=a.folder, repo_id=repo, commit_message=a.message)
print(f"UPLOADED https://huggingface.co/{repo}")
`;

function summarizeDir(dir: string): { lines: string[]; totalMb: number } {
  const lines: string[] = [];
  let total = 0;
  const walk = (d: string, prefix: string) => {
    for (const entry of readdirSync(d)) {
      const full = path.join(d, entry);
      const st = statSync(full);
      if (st.isDirectory()) walk(full, `${prefix}${entry}/`);
      else {
        total += st.size;
        if (lines.length < 30) lines.push(`${prefix}${entry} (${(st.size / 1024 / 1024).toFixed(2)} MB)`);
      }
    }
  };
  walk(dir, '');
  return { lines, totalMb: total / 1024 / 1024 };
}

registerTool<{ local_dir: string; repo_id: string; private?: boolean; commit_message?: string }>({
  name: 'hf_upload',
  description:
    'Upload a model folder to the Hugging Face Hub. The USER is asked for approval every time — never assume consent. Make sure output/model/README.md (the model card) exists first.',
  inputSchema: z.object({
    local_dir: z.string().min(1).describe('Workspace-relative folder to upload (e.g. output/model).'),
    repo_id: z.string().regex(/^[\w.-]+\/[\w.-]+$/, 'expected "user/repo"'),
    private: z.boolean().optional(),
    commit_message: z.string().max(200).optional(),
  }),
  parallelSafe: false,
  async execute(input, ctx) {
    if (!ctx.cfg.hfToken) {
      return { text: 'HF_TOKEN is not set in .env — ask the user to add it and restart, or offer local-only export.', isError: true };
    }
    const dir = resolveInWorkspace(ctx.workspaceDir, input.local_dir);
    if (!existsSync(dir)) return { text: `no such folder: ${input.local_dir}`, isError: true };

    const { lines, totalMb } = summarizeDir(dir);
    const approved = await ctx.manager.requestApproval({
      sessionId: ctx.sessionId,
      agentRunId: ctx.agentRunId,
      tool: 'hf_upload',
      summary: `Publish to huggingface.co/${input.repo_id} (${input.private ? 'private' : 'PUBLIC'})`,
      body: `Upload ${input.local_dir} → ${input.repo_id}\nTotal: ${totalMb.toFixed(1)} MB\n\n${lines.join('\n')}`,
      payload: { repo_id: input.repo_id },
    });
    if (!approved) {
      return { text: 'User DENIED the upload. Keep the model local (register_model) and ask if they want anything changed.', isError: true };
    }

    const scriptPath = path.join(ctx.workspaceDir, 'scripts', '_hf_upload.py');
    mkdirSync(path.dirname(scriptPath), { recursive: true });
    writeFileSync(scriptPath, UPLOAD_PY, 'utf8');

    const res = await runForeground({
      command:
        `uv run --with huggingface_hub python scripts/_hf_upload.py ` +
        `--folder "${dir}" --repo "${input.repo_id}"` +
        (input.private ? ' --private' : '') +
        (input.commit_message ? ` --message "${input.commit_message.replace(/"/g, "'")}"` : ''),
      cwd: ctx.workspaceDir,
      timeoutMs: 3_600_000, // big LFS uploads
      env: { HF_TOKEN: ctx.cfg.hfToken },
      abort: ctx.abort,
    });
    if (res.exitCode !== 0) {
      return { text: `upload failed (exit ${res.exitCode}):\n${res.output.slice(-1_500)}`, isError: true };
    }
    ctx.bus.emit(
      ctx.sessionId,
      'agent.artifact',
      { artifactKind: 'model-card', label: input.repo_id, path: `https://huggingface.co/${input.repo_id}` },
      ctx.agentRunId,
    );
    return { text: `Upload complete: https://huggingface.co/${input.repo_id}\n${res.output.slice(-400)}` };
  },
});
